liba{anyany}: include/hxx{**} hxx{version} include/anyany/mxx{anyany}

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_base/include"

# Export options.
#
liba{anyany}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_base/include"
}

include/
{
	hxx{*}:
	{
	  install         = include/
	  install.subdirs = true
	}
}
